### ISSUE TITLE
[PrimaryTextCard-PlannerTasks]: [getPlanInfo is giving 404 error]

### ISSUE THREAD

**Issue by PanchamiM** [pnp/sp-dev-fx-aces#146] opened 2023-06-29 13:26 UTC
Adaptive Card: PrimaryTextCard-PlannerTasks
Issue: After getting all the tasks from graph api, for each task we are getting plan name and it is erroring out for some users.
Error: 404
Completer Error Log: {"statusCode":404,"code":"","message":"The requested item is not found.","requestId":"","date":"2023-06-29T09:44:29.000Z","body":"{\"code\":\"\",\"message\":\"The requested item is not found.\",\"innerError\":{\"date\":\"2023-06-29T11:44:29\",\"request-id\":\"\",\"client-request-id\":\"\"}}"}
Environment: Production
Method Name: public async getPlanInfo(planId: string): Promise<MicrosoftGraph.PlannerPlan> {
File name where method is : GraphService.ts
Behaviour: The issue is intermediate
![Error](https://github.com/pnp/sp-dev-fx-aces/assets/117371226/73348c61-2aed-43e5-95fa-1c2474b2d263)

**Comment by dcashpeterson** [comment] 2023-06-29 13:59
@PanchamiM did you check and make sure that the graph permissions were granted in the api admin center?

**Comment by PanchamiM** [comment] 2023-06-29 14:02
@dcashpeterson yes the permissions are assigned. It is working for majority of users. But some users are facing this issue.

**Comment by PanchamiM** [comment] 2023-06-30 05:05
Any update on this.

**Comment by PanchamiM** [comment] 2023-07-04 04:03
Any update on this.

**Comment by PanchamiM** [comment] 2023-07-05 09:51
This issue is being observed in Prod. Please anyone has any idea on this.

**Comment by anoopt** [comment] 2023-07-05 10:23
Hi @PanchamiM - Just wanted to confirm if you have consented the permissions as per the instructions? - https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-PlannerTasks#prerequisites

Also can you please take a look at this short video which shows the demo of the sample to see if find any relevant information? - https://www.youtube.com/watch?v=_1WNf4-GZiY&ab_channel=Microsoft365%26PowerPlatformCommunity

**Comment by PanchamiM** [comment] 2023-07-06 04:38
Hi @anoopt Below are the permissions assigned in the admin center.
Tasks.Read
Tasks.ReadWrite
Group.ReadWrite.All

This should be fine right?

**Comment by anoopt** [comment] 2023-07-06 07:27
Yes.

When the users (or you) open to the planner (https://tasks.office.com) do the they see the plan (that is configured in the ACE properties - Select Planner plan) ?

**Comment by PanchamiM** [comment] 2023-07-06 08:33
By default we have set the All Plans options.

**Comment by anoopt** [comment] 2023-07-06 16:51
Ok @PanchamiM . I am not able to replicate this issue in my tenant. So can you please confirm if users are able to access the planner from https://tasks.office.com?

**Comment by PanchamiM** [comment] 2023-07-07 06:22
@anoopt  yes I am able to the Planner from the give URL. This is not happening to all users, only some of the users are facing it and it is intermediate.

**Comment by PanchamiM** [comment] 2023-07-10 05:16
Any update on this.

**Comment by PanchamiM** [comment] 2023-07-11 08:38
@dcashpeterson  The Ace is not configured with any plan ID. It is supposed to query all the tasks.
As per my understanding and the way I tested in dev environment whenever a user is added to a task they will be given the access to the Plan also.
The users are from client side and it will be difficult to connect with them. Anyway I will check if we can get anything.

**Comment by PanchamiM** [comment] 2023-07-18 04:13
We cannot connect with the clients. Any breakthrough in this?

**Comment by dcashpeterson** [comment] 2023-07-18 09:47
@PanchamiM without more information we can't provide any more guidance. This looks like an issue with permissions of some sort so without actually reproducible steps or access to info from the users we can't provide any more assistance. I am going to go ahead and close this issue. If you get more info from the users or can provide us with reproducible steps please open a new issue and reference this one.

**Closed by dcashpeterson** 2023-07-18 09:47 UTC
